spring:
    datasource:
        driver : org.mariadb.jdbc.Driver
        url : @db.url@
        username : @db.user@
        password : @db.pass@
    mvc:
        view:
            prefix : /WEB-INF/views/
            suffix : .jsp
mybatis:
    type-aliases-package : com.example.demo.dto
    mapper-locations : mapper/xml/*.xml 

        